version: '3.8'

services:
  db:
    image: postgres:15.0-alpine
    container_name: ado-db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    networks:
      - pgnetwork
    volumes:
      - pg_volume:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  adonis_app:
    container_name: adonis_app
    restart: always
    depends_on:
      - db
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    environment:
      - DB_HOST=db
    networks:
      - pgnetwork
    volumes:
      - ./:/home/node/app
    command: dumb-init node ace serve --watch
volumes:
  pg_volume:
networks:
  pgnetwork:
    driver: bridge
